version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "80:80"
  server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
